### ISSUE TITLE
Updat PowershellGalary to 3.10.0

### ISSUE THREAD

**Issue by AlkHacNar** [JonathanPitre/PSADT#3]
Hey Jonathan,

I don't know how long it takes, till an update in PSGallery is approved. But did you already upoloaded it, or didn't had time for it?

Greetings 

Alexej

**Comment by AlkHacNar** [comment]
or update to3.10.1 directly after the pull request

**Comment by JonathanPitre** [comment]
Done

https://www.powershellgallery.com/packages/PSADT/3.10.1
